### ISSUE TITLE
проблема с sensi.org/scalar/categories/all/

### ISSUE THREAD

**Issue by grayich** [svofski/incursiondelrio#1]
Не нашёл куда можно было ещё сообщить, обратная связь отсутствует )

на сайте просрочен сертификат, из за этого не работают игры на сайте
к примеру  http://sensi.org/scalar/ware/897/

пришлось напрямую открыть в браузере https://www.sensi.org/scalar/media/w/incurzion.rom  дабы он ругнулся на сертификат и после этого отправить его в игнор, после этого заработали игры на сайте

сайт по http работает, а в коде  прописано https

**Comment by svofski** [comment]
Привет! Спасибо. Сертификат должны скоро обновить. А пока можно или добавить исключение на www.sensi.org, ну или подождать.

**Comment by grayich** [comment]
да, так и сделал, но некоторое время думал, что просто виртуалка сломана )
как и большинство посетителей наверно

з.ы.
звук щелчки - это нормально или только у меня?
регулятор уровня звука кстати тоже лишним не будет )
